Server:
  # development 开发模式 production 生产模式
  AppMode: production
  Host: localhost
  Port: 80
  # Jwt加密秘钥
  JwtKey:
  Database:
    Type: mysql
    Host: localhost
    Port: 2333
    User: root
    PassWord:
    Name: vblog
    Redis:
      Host: localhost
      Port: 2677
      Password:
      Db: 0
  Oss:
    #oss服务商，支持[qiniu,aliyun]
    Name: aliyun
    qiniu:
      AccessKey:
      SecretKey:
      Bucket:
      Sever:
    aliyun:
      AccessKeyId:
      AccessKeySecret:
      Endpoint: oss-rg-china-mainland.aliyuncs.com
      BucketName: rainyaftertomorrow
  Push:
    # 启用哪个,空或其他为不启用
    Enable: Email
    # 企业微信推送
    # 需要注意企业微信，后面新建的应用必须要ip白名单，不然用不了
    WxPush:
      CorpId:
      Agentid:
      Secret:
    # 邮箱
    Email:
      # 发送方和授权码
      From:
      Password:
      # 不填默认发给自己
      To:
      Host: smtp.qq.com
      Port: 25

Log:
  # 是否启用
  Enable: true
  # 日志等级 生产环境推荐 warn
  Level: warn
  # 日志文件名
  Filename: log/log.log
  # 最大大小
  MaxSize: 10
  # 最长时间
  MaxAge: 28
  # 最大备份
  MaxBackups: 5
  # 是否压缩
  Compress: false
SiteInfo:
  # 网址带 http,用于生成站点地图
  Url: http://www.ipoluo.com
  # 博客名
  Name: 后天有雨
  # 博主名
  User: 画中蝉
  # 邮箱地址
  Email: 951319124@qq.com
  # 博客描述
  Desc: 真的是你鸭！~
  # 建站时间 秒级时间戳 2022-09-07T12:39:08+08:00
  ConstructionTime: 1701869396